version: '3.9'
services:
  db:
    image: postgres:16
    container_name: nest_crud_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: nest_crud
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest1
    
    ports:
      - "3306:5432"  # Porta padrão do MySQL
    volumes:
      - pgdata_data:/var/lib/poatgresql/data  

volumes:
  pgdata_data:  

